// used any time a template is missing an icon
export const DEFAULT_TEMPLATE_ICON_URL = "/default-template-icon-64px.png";

// Represents the basic information about a template, hopefully small enough for lightweight queries for the search and
// filter features. This way the long strings about template section items could be retrieved only once the template is
// being viewed, not previewed with others
export type Template = {
  id: number;
  name: string;
  author: string;
  imageUrl?: string;
}

// Represents a group of checklist items that were generated by the AI or are in an existing template
export type TemplateSection  = {
  sectionName: string;
  sectionDescription: string;
  sectionItems: TemplateSectionItem[];
}

// Represents a single checklist item and is set to singleLineText by default
export type TemplateSectionItem = {
  answerOptions: string[];
  fieldTitle: string;
  fieldDetails: string;
  fieldType: "singleLineText" |
      "multiLineText" |
      "number" |
      "date" |
      "slider" |
      "radio" |
      "checkBoxGroup"
}


